version: '3'

services:
  app:
    image: statonlab/tripal3:latest
    ports:
      - "8083:80"
    volumes:
      - .:/modules/tripal_galaxy
  galaxy:
    image: 'bgruening/galaxy-stable:18.09'
    ports:
      - "8084:80"
